apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order
          # Image will be overridden to ACR in Stage 2
          image: nginx:1.25
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: order-db
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            # order-service talks to product-service
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8001
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
